# Generated by Django 4.2 on 2023-04-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='meal_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
